server:
  port: 8080
  servlet:
    session:
      cookie:
        name: common-admin
      timeout: 1800 #单位秒
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://localhost:3306/admin_common?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:

redis:
  host: localhost
  port: 6379
  # 密码（默认为空）
  password:
  maxIdle: 10
  minIdle: 5
  timeout: 1000
  dbs: 0,1,2,3,4,5,6,7,8,8,10,11,12,13,14,15      # 可以指定多个，用“,”隔开，写在第一个的为defaultDB

login:
  loginPath: /login
  logoutPath: /logout